version: '3.9'

services:
  erunout:
    container_name: erunout-server
    build: .
    restart: unless-stopped
    privileged: true
    ports:
      - 80:3000
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/erunout

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      
  wifi-ap:
    image: sdelrio/rpi-hostap:latest
    privileged: true
    restart: unless-stopped
    environment:
      SSID: ${SSID}
      WPA_PASSPHRASE: ${WPA_PASSPHRASE}
      INTERFACE: wlan0
      CHANNEL: 6
      AP_ADDR: 10.0.10.1
      SUBNET: 10.0.10.0
      OUTGOINGS: eth0
    network_mode: host