version: '3.9'

services:
  dev-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEV_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DEV_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: erunout
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/dev_init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  dev-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - dev-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DEV_MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DEV_MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DEV_MONGODB_USERNAME}:${DEV_MONGODB_PASSWORD}@dev-mongo:27017/