version: '3.9'

services:
  erunout:
    container_name: erunout-server
    build: .
    restart: unless-stopped
    privileged: true
    depends_on:
      - mongo
    ports:
      - 80:3000
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/erunout

  mongo:
    image: mongo:4.4-rc
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: erunout
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /data/db
      
  wifi-ap:
    image: sdelrio/rpi-hostap:latest
    privileged: true
    restart: unless-stopped
    environment:
      SSID: ${SSID}
      WPA_PASSPHRASE: ${WPA_PASSPHRASE}
      INTERFACE: wlan0
      CHANNEL: 6
      AP_ADDR: 10.0.10.1
      SUBNET: 10.0.10.0
      OUTGOINGS: eth0
    network_mode: host